                </div>
              </div>
            </div>
          </td>

          <td id="portal-column-two">
            &nbsp;
        </tr>
      </tbody>
    </table>

    <div class="visualClear">
      <!-- -->
    </div>
    <hr class="netscape4" />

    <div id="portal-footer">
      <p><b><a href="http://www.exploreveg.org/">Compassionate
      Action for Animals</a></b> / P.O. Box 13149 / Mpls, MN 55414
      / 612-276-2242 / <a href=
      "mailto:info@exploreveg.org">info@ExploreVeg.org</a></p>
    </div>

    <div id="portal-colophon">
      <!--

        Please keep the Plone Powered button (or a textual link to us) if you use
        Plone on your site. It's a nice token of gratitude, and we appreciate your
        help in promoting the Plone name.

        Plone is powered by the combined forces of Zope and CMF, two absolutely
        great systems made by Zope Corporation (http://zope.com) and they in turn
        are based on the best programming language in the world - Python
        (http://www.python.org). We owe these guys a lot, thanks for making Plone
        possible!

      -->
       <a href="http://plone.org/" class="colophonIcon" title=
      "This Plone site was built using Plone, the Open Source Content Management System. Click for more information."
      style=
      "background-image: url(http://www.exploreveg.org/plone_powered.gif);">
      Powered by Plone, the Open Source Content Management
      System</a>

      <p class="discreet">This site conforms to the following
      standards:</p>

      <div class="colophonWrapper">
        <ul>
          <li><a href="http://www.section508.gov/" class=
          "colophonIcon" title=
          "This Plone site conforms to the US Government Section 508 Accessibility Guidelines."
          style=
          "background-image: url(http://www.exploreveg.org/colophon_sec508.gif);">
          Section 508</a></li>

          <li><a href="http://www.w3.org/WAI/WCAG1AA-Conformance"
          class="colophonIcon" title=
          "This Plone site conforms to the W3C-WAI Web Content Accessibility Guidelines."
          style=
          "background-image: url(http://www.exploreveg.org/colophon_wai-aa.gif);">
          WCAG</a></li>

          <li><a href="http://validator.w3.org/check/referer"
          class="colophonIcon" title=
          "This Plone site is valid XHTML." style=
          "background-image: url(http://www.exploreveg.org/colophon_xhtml.png);">
          Valid XHTML</a></li>

          <li><a href=
          "http://jigsaw.w3.org/css-validator/check/referer" class=
          "colophonIcon" title=
          "This Plone site was built with valid CSS." style=
          "background-image: url(http://www.exploreveg.org/colophon_css.png);">
          Valid CSS</a></li>

          <li><a href="http://plone.org/browsersupport" class=
          "colophonIcon" title=
          "This Plone site is usable in any web browser." style=
          "background-image: url(http://www.exploreveg.org/colophon_anybrowser.png);">
          Usable in any browser</a></li>
        </ul>
      </div>
    </div>
  </div>

  <div id="errors" style="display: none">

  </div>

</body>
</html>
