<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta name="generator" content=
  "HTML Tidy for Linux (vers 6 November 2007), see www.w3.org" />
  <meta http-equiv="Content-Type" content=
  "text/html; charset=utf-8" />

  <title>Banquet 2010 &mdash; Compassionate Action for Animals</title>

  <meta name="generator" content="Plone - http://plone.org" />
  <script type="text/javascript" src="/jquery-1.4.2.min.js"></script>
  <script type="text/javascript" src="/jquery-ui-1.8rc2.custom.min.js"></script>
  <script type="text/javascript" src="/jquery.colorbox-min.js"></script>
  <script type="text/javascript" src="/signup.js"></script>
  <style type="text/css">
/*<![CDATA[*/
  <!-- @import url(/exploreveg-1.css); -->
  /*]]>*/
  </style>
  <link rel="alternate stylesheet" type="text/css" media="screen"
  href="/textSmall.css" title="Small Text" />
  <link rel="alternate stylesheet" type="text/css" media="screen"
  href="/textLarge.css" title="Large Text" />
  <style type="text/css">
/*<![CDATA[*/
  <!-- @import url(/exploreveg-2.css); -->
  /*]]>*/
  </style>
  <link rel="alternate stylesheet" type="text/css" media="screen"
  href="/ploneTextSmall.css" title="Small Text" />
  <link rel="alternate stylesheet" type="text/css" media="screen"
  href="/ploneTextLarge.css" title="Large Text" />
  <style type="text/css" media="all">
/*<![CDATA[*/
  <!-- @import url(/ploneCustom.css); -->
  /*]]>*/
  </style>
  <!-- Internet Explorer CSS Fixes + IE7 for compliance fixes (limited set) -->
  <!--[if lt IE 7]>
        <style type="text/css" media="all">@import url(/IEFixes.css);</style>
    <![endif]-->
  <link rel="shortcut icon" type="image/x-icon" href=
  "http://www.exploreveg.org/favicon.ico" />
  <link type="text/css" media="screen" rel="stylesheet" href="/colorbox.css" />
  <link rel="home" href="http://www.exploreveg.org" title=
  "Front page" />
  <link rel="search" title="Search this site" href=
  "http://www.exploreveg.org/search_form" />
  <link rel="author" title="Author information" href=
  "http://www.exploreveg.org/author/greg" />
  <link rel="contents" href="http://www.exploreveg.org/sitemap"
  title="Site Map" />
  <link rel="up" href="http://www.exploreveg.org" title=
  "Up one level" /><!-- Disable IE6 image toolbar -->
  <meta http-equiv="imagetoolbar" content="no" />

  <style type="text/css">
    #content{
      margin-top: 0 !important;
      padding-top: 0 !important;
    }

    #region-content{
      margin-top: 0 !important;
      padding-top: 0 !important;
    }

    .image-with-caption {
      clear: right;
      float: right;
      margin-left: 1em;
    }

    .image-with-caption img {
      border: 1px solid black;
      width: 150px;
    }

    div.caption {
      font-size: 80%;
      font-style: italic;
    }

    #attendees-form {
      margin-bottom: 1em;
    }

    .form-item {
      margin-top: 1em;
    }

    .radio-list {
      margin-top: 0.3em;
    }

    .radio-list li {
      list-style: none;
    }

    .radio-list li label {
      font-weight: normal;
    }

    #add-another-p {
      margin-top: 1em;
    }

    .ui-dialog {
      border: 1px solid black;
      background-color: #f9f9f9;
    }

    .ui-dialog-titlebar {
      background-color: #f90;
      padding: 0.5em;
    }

    .ui-dialog-title {
      font-size: 110%;
      font-weight: bold;
    }

    .ui-dialog-titlebar-close {
      color: black;
      float: right;
      text-decoration: none;
    }

    #errors {
      padding-top: 1em;
    }

    #errors ul {
      list-style: disc;
      margin-top: 0;
    }

  </style>
</head>

<body class="section-template" dir="ltr">
  <div id="visual-portal-wrapper">
    <div id="portal-top">
      <div id="portal-header">
        <a class="hiddenStructure" accesskey="2" href=
        "http://www.exploreveg.org/caa/template#documentContent">Skip
        to content.</a> <a class="hiddenStructure" accesskey="6"
        href=
        "http://www.exploreveg.org/caa/template#portlet-navigation-tree">
        Skip to navigation</a>

        <ul id="portal-siteactions">
          <li id="siteaction-sitemap"><a href=
          "http://www.exploreveg.org/sitemap" accesskey="3" title=
          "Site Map">Site Map</a></li>

          <li id="siteaction-accessibility"><a href=
          "%20http://www.exploreveg.org/accessibility-info"
          accesskey="0" title=
          "Accessibility">Accessibility</a></li>

          <li id="siteaction-contact"><a href=
          "%20http://www.exploreveg.org/contact-info" accesskey="9"
          title="Contact">Contact</a></li>
        </ul>

        <div id="portal-searchbox">
          <form name="searchform" action=
          "http://www.exploreveg.org/search" style=
          "white-space:nowrap" onsubmit="return liveSearchSubmit()"
          id="searchform">
            <label for="searchGadget" class=
            "hiddenStructure">Search Site</label>

            <div class="LSBox">
              <input id="searchGadget" tabindex="30001" name=
              "SearchableText" type="text" size="15" title=
              "Search Site" accesskey="4" class=
              "visibility:visible" /> <input class="searchButton"
              type="submit" tabindex="30002" value="Search" />

              <div class="LSResult" id="LSResult" style="">
                <div class="LSShadow" id="LSShadow"></div>
              </div>
            </div>
          </form>

          <div id="portal-advanced-search" class="hiddenStructure">
            <a href="http://www.exploreveg.org/search_form"
            accesskey="5">Advanced Search&hellip;</a>
          </div>
        </div>

        <h1 id="portal-logo"><a href="http://www.exploreveg.org"
        accesskey="1">Compassionate Action for Animals</a></h1>

        <div id="portal-skinswitcher"></div>

        <h5 class="hiddenStructure">Sections</h5>

        <ul id="portal-globalnav">
          <li id="portaltab-index_html" class="selected"><a href=
          "http://www.exploreveg.org" title="">Home</a></li>

          <li id="portaltab-do" class="plain"><a href=
          "http://www.exploreveg.org/do" title="">What We
          Do</a></li>

          <li id="portaltab-help" class="plain"><a href=
          "http://www.exploreveg.org/help" title="">How to
          Help</a></li>

          <li id="portaltab-issues" class="plain"><a href=
          "http://www.exploreveg.org/issues" title="">The
          Issues</a></li>

          <li id="portaltab-resources" class="plain"><a href=
          "http://www.exploreveg.org/resources" title="">Vegetarian
          Resources</a></li>

          <li id="portaltab-events" class="plain"><a href=
          "http://www.exploreveg.org/events" title="">Events</a></li>

        </ul>
      </div>

      <h5 class="hiddenStructure">Personal tools</h5>

      <ul id="portal-personaltools">
        <li class="portalNotLoggedIn">&nbsp;</li>
      </ul>

      <div id="portal-breadcrumbs">
        <span id="breadcrumbs-you-are-here">You are here:</span>
        <a href="http://www.exploreveg.org">Home</a> <span class=
        "breadcrumbSeparator">&rarr;</span> <span dir=
        "ltr"><span>Banquet 2010</span></span>
      </div>
    </div>

    <div class="visualClear">
      <!-- -->
    </div>

    <table id="portal-columns">
      <tbody>
        <tr>
          <td id="portal-column-one">
            &nbsp;
          </td>

          <td id="portal-column-content">
